/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jin_jin_MainActivity */

#ifndef _Included_jin_jin_MainActivity
#define _Included_jin_jin_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef jin_jin_MainActivity_BIND_ABOVE_CLIENT
#define jin_jin_MainActivity_BIND_ABOVE_CLIENT 8L
#undef jin_jin_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define jin_jin_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef jin_jin_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define jin_jin_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef jin_jin_MainActivity_BIND_AUTO_CREATE
#define jin_jin_MainActivity_BIND_AUTO_CREATE 1L
#undef jin_jin_MainActivity_BIND_DEBUG_UNBIND
#define jin_jin_MainActivity_BIND_DEBUG_UNBIND 2L
#undef jin_jin_MainActivity_BIND_EXTERNAL_SERVICE
#define jin_jin_MainActivity_BIND_EXTERNAL_SERVICE -2147483648L
#undef jin_jin_MainActivity_BIND_IMPORTANT
#define jin_jin_MainActivity_BIND_IMPORTANT 64L
#undef jin_jin_MainActivity_BIND_NOT_FOREGROUND
#define jin_jin_MainActivity_BIND_NOT_FOREGROUND 4L
#undef jin_jin_MainActivity_BIND_WAIVE_PRIORITY
#define jin_jin_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef jin_jin_MainActivity_CONTEXT_IGNORE_SECURITY
#define jin_jin_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef jin_jin_MainActivity_CONTEXT_INCLUDE_CODE
#define jin_jin_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef jin_jin_MainActivity_CONTEXT_RESTRICTED
#define jin_jin_MainActivity_CONTEXT_RESTRICTED 4L
#undef jin_jin_MainActivity_MODE_APPEND
#define jin_jin_MainActivity_MODE_APPEND 32768L
#undef jin_jin_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define jin_jin_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef jin_jin_MainActivity_MODE_MULTI_PROCESS
#define jin_jin_MainActivity_MODE_MULTI_PROCESS 4L
#undef jin_jin_MainActivity_MODE_NO_LOCALIZED_COLLATORS
#define jin_jin_MainActivity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef jin_jin_MainActivity_MODE_PRIVATE
#define jin_jin_MainActivity_MODE_PRIVATE 0L
#undef jin_jin_MainActivity_MODE_WORLD_READABLE
#define jin_jin_MainActivity_MODE_WORLD_READABLE 1L
#undef jin_jin_MainActivity_MODE_WORLD_WRITEABLE
#define jin_jin_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef jin_jin_MainActivity_DEFAULT_KEYS_DIALER
#define jin_jin_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef jin_jin_MainActivity_DEFAULT_KEYS_DISABLE
#define jin_jin_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef jin_jin_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define jin_jin_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef jin_jin_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define jin_jin_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef jin_jin_MainActivity_DEFAULT_KEYS_SHORTCUT
#define jin_jin_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef jin_jin_MainActivity_RESULT_CANCELED
#define jin_jin_MainActivity_RESULT_CANCELED 0L
#undef jin_jin_MainActivity_RESULT_FIRST_USER
#define jin_jin_MainActivity_RESULT_FIRST_USER 1L
#undef jin_jin_MainActivity_RESULT_OK
#define jin_jin_MainActivity_RESULT_OK -1L
/*
 * Class:     jin_jin_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jin_jin_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     jin_jin_MainActivity
 * Method:    getString_From_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jin_jin_MainActivity_getString_1From_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
